### DISCUSSION TITLE
How to add a custom font?

### DISCUSSION THREAD

**Discussion by carloscabanero** [blinksh/blink#1540] [Q&A] [answered]
How do I add my favorite font to Blink Shell? How about Nerd fonts?

**Comment by carloscabanero** [comment, marked as answer]
# How to add custom font?

The simplest way to add custom fonts inside Blink Shell is by using CSS. The fonts can be loaded from a remote server, or by converting them to base64. Nerd fonts should work without issue following this method. You can browse our [gallery](https://github.com/blinksh/fonts) to see if we can already save you some work.

### Base64

To convert your fonts, we recommend [the Transfonter](https://transfonter.org/) tool. It will automatically generate a stylesheet you can import right into Blink Shell. Or by using any other converter and manually the following CSS. You can upload the CSS as a Gist for easier access.

```css
@font-face {
 font-family: "Fira Code";
 font-style: normal;
 font-weight: 200;
 src: url(data:font/woff;charset=utf-8;base64,<base64 dump>);
}
@font-face {
 font-family: "Fira Code";
 font-style: normal;
 font-weight: 400;
 src: url(data:font/woff;charset=utf-8;base64,<base64 dump>);
}
```

### Remote font

The second option is loading it from a remote server. This way has its downsides. If you move the font, the local installation will break, and you'll need to reconfigure and import it again.

```css
@font-face {
 font-family: "Fira Code";
 font-weight: 400;
 src: url('https://example.com/fonts/fira_code_regular.otf' format('opentype'));
}
@font-face {
 font-family: "Fira Code";
 font-weight: 600;
 src: url('https://example.com/fonts/fira_code_medium.ttf' format('truetype'));
}
@font-face {
 font-family: "Fira Code";
 font-weight: 800;
 src: url('https://example.com/fonts/fira_code_bold.woff' format('woff'));
}
```

### Importing the font to Blink Shell

Inside settings, click the `Appearance` and slide down to the Fonts section. Click the `Add a new font` button.

![IMG_2344.jpeg](https://res.craft.do/user/full/0ef94637-30d5-80f2-9fa1-0089b763dcf6/EC3ACE0A-09D8-4CA5-A77B-66CF262DEC9B_2/xR2Z7ZHEJczKz4y4kVWsl4nTEy4Q95krTnYd1FKumcMz/IMG_2344.jpeg)

Add a name for it and insert a link to the stylesheet. We recommend using GitHub Gist for that. Click import, and that's it!

![IMG_2345.png](https://res.craft.do/user/full/0ef94637-30d5-80f2-9fa1-0089b763dcf6/44D34F63-C6CF-45BC-A983-E166800E3841_2/VTOZHJf49TqQBREG1YvcyRPZKJcMrMvF0zjxZJn97RAz/IMG_2345.png)

You can now select it from settings, open a new window of Blink Shell and enjoy your new font.

### More information
- https://docs.blink.sh/advanced/creating-fonts-and-themes
- MDN article about `@font-face`: [https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face)
- CSS-Tricks: How to use @font-face in CSS: [https://css-tricks.com/snippets/css/using-font-face-in-css/](https://css-tricks.com/snippets/css/using-font-face-in-css/)
