### ISSUE TITLE
Be able to add glow synthwave effects theme to blink

### ISSUE THREAD

**Issue by remiconnesson** [blinksh/blink#1478]
Would be lovely if we could get some glow synthwave theme in blink.sh

![image](https://user-images.githubusercontent.com/28846642/168776150-8caf30cc-a795-4e0e-990d-3f621f9af1a6.png)

references:
https://github.com/atomiks/moonlight-vscode-theme/issues/6
https://github.com/robb0wen/synthwave-vscode#to-enable-the-glow

**Comment by yury** [comment]
You can target .c0-.c16 colors with custom css.

For instance:
```css
span.c3 {
   color: rgb(196, 160, 0);
   text-shadow: #FC0 1px 0 10px;
}
```

will give you glow effect:
![2022-05-17 14 26 44](https://user-images.githubusercontent.com/5250/168800498-dfa80528-645f-4ef1-9fa7-1b03f316dd53.jpg)
