### ISSUE TITLE
Double-Width glyphs not showing properly

### ISSUE THREAD

**Issue by sambadevi** [blinksh/blink#498]
When using double-width glyphs (for example `\uf015` with nerd-fonts) the glyphs are chopped off.

**Comment by yury** [comment]
Hi @sambadevi,

What font are you using?
Can you make screenshot?

**Comment by sambadevi** [comment]
The font is Roboto Mono Light Nerd Font.

Font Size is 12, but the font-size doesn't matter, the glyphs are cut either way

Screenshot including echo of the home symbol:
![Imgur](https://i.imgur.com/uXPzo4o.png)

The custom stylesheet looks like this:
```css
@font-face {
    font-family: "RobotoMono Nerd Font";
    font-style: normal;
    font-weight: 200;
    src: url(https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/RobotoMono/Light/complete/Roboto%20Mono%20Light%20Nerd%20Font%20Complete.ttf?raw=true);
}
@font-face {
    font-family: "RobotoMono Nerd Font";
    font-style: normal;
    font-weight: 400;
    src: url(https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/RobotoMono/Light/complete/Roboto%20Mono%20Light%20Nerd%20Font%20Complete.ttf?raw=true);
}
@font-face {
    font-family: "RobotoMono Nerd Font";
    font-weight: 600;
    src: url(https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/RobotoMono/Light/complete/Roboto%20Mono%20Light%20Nerd%20Font%20Complete.ttf?raw=true);
}
@font-face {
    font-family: "RobotoMono Nerd Font";
    font-weight: 800;
    src: url(https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/RobotoMono/Light/complete/Roboto%20Mono%20Light%20Nerd%20Font%20Complete.ttf?raw=true);
}
```
