### ISSUE TITLE
Can’t seem to get all-the-icons to work

### ISSUE THREAD

**Issue by tdegrunt** [blinksh/blink#771]
Hello,

I’m trying to get all-the-icons to work under Emacs within Blink, but I can’t seem to be able to get this to work: Things I tried:

- created the below file and tried adding this to Blink
- added all the icons to a profile with AnyFont

I’m probably misunderstanding how this works, or doing something wrong. Can someone give me some pointers or just explain why this won’t work?

Regards,
Tom

```css
@font-face {
    font-family: "all-the-icons"
    font-style: normal;
    font-weight: 200;
    src: url('https://raw.githubusercontent.com/domtronn/all-the-icons.el/master/fonts/all-the-icons.ttf');
}
@font-face {
    font-family: "file-icons";
    font-weight: 200;
    src: url('https://raw.githubusercontent.com/domtronn/all-the-icons.el/master/fonts/file-icons.ttf');
}
@font-face {
    font-family: "FontAwesome";
    font-style: normal;
    font-weight: 200;
    src: url('https://raw.githubusercontent.com/domtronn/all-the-icons.el/master/fonts/fontawesome.ttf');
}
@font-face {
    font-family: "Material Icons";
    font-weight: 200;
    src: url('https://raw.githubusercontent.com/domtronn/all-the-icons.el/master/fonts/material-design-icons.ttf');
}
@font-face {
    font-family: "github-octicons";
    font-weight: 200;
    src: url('https://raw.githubusercontent.com/domtronn/all-the-icons.el/master/fonts/all-the-icons.ttf');
}
@font-face {
    font-family: "Weather Icons";
    font-weight: 200;
    src: url('https://raw.githubusercontent.com/domtronn/all-the-icons.el/master/fonts/weathericons.ttf');
}
```
